Update README
naka-no-mura/z_shihan pull request #1
Opened 2020-11-24 21:42 UTC by naka-no-mura

# Z-SHIHAN（ジー・シハン）
# サービス概要
仕入・在庫管理・販売を担うビジネスパーソンのために  
仕入単価と販売単価も同時に管理することで、売買損益をリアルタイムで把握かつ棚卸し業務の時間短縮ができる  
在庫管理と収支管理の一体型サービスです

# 登場人物
- 仕入業務を行う人
- 在庫管理を行う人
- 販売業務を行う人

# ユーザーが抱える問題
- 仕入・在庫管理・販売の全てを同一人物または小数人で行う場合、手間がかかりすぎる
- 棚卸しをしないと収支が把握できない。（リアルタイムで収支を把握できない）
- どの販売先でどのくらい売買損益が発生しているのかをパッと見で把握できない

# 解決方法
- 仕入：仕入価格を入力する（個別データの入力もCSV形式の価格表の取込も可能）
- 在庫：入庫・出荷毎に値を入力する
- 販売：販売価格を入力する（個別データの入力もCSV形式の価格表の取込も可能）
- 仕入・在庫・販売の状況を自動で計算し、リアルタイムで収支を管理する

# プロダクト
仕入・在庫管理・販売をまとめて行うことができるWebアプリケーション

# 他サービスとの違い
- 販売先によって販売額も設定できるため、売買損益が確認できる
- 売買損益が確認できるため、営業マンのための在庫管理サービスとなる得る  
（販売先Aでこれだけ収益が出ているから、販売先Bでは販売単価を下げて数量拡大に努めよう、という戦略が立てられる）

# マーケット
仕入・在庫管理・販売の一連の流れを同一人物または小数人で行うような、小規模な事業関係者

# 悩んでいること
- 現在庫数量の自動計算をどうするか。今のままだと、入荷データと出荷データの判別ができず、入荷データと出荷データの数量の合計が表示されてしまう。  
→入出荷データを、入荷データ一覧と出荷データ一覧に切り分けて、それぞれの合計数量で引算する方が良さそうか。

- 全く別の会社が新たに登録したときに、すでにあるデータを見えなくする方法  
→模索中

2020-11-25 06:37 UTC, yuji91 requested changes
こちらREADMEについて、気になった点をコメントしました。

内容のご確認をお願いします！

2020-11-25 06:37 UTC, yuji91 commented on README.md
> +（販売先Aでこれだけ収益が出ているから、販売先Bでは販売単価を下げて数量拡大に努めよう、という戦略が立てられる）
「売買損益が確認できる」ことで「営業マンのための在庫管理サービスとなる」ことの関連性がうまく理解できませんでした。
ここでいう「営業マン」とは「仕入、在庫管理、販売」を行なっているということでしょうか。

2020-11-25 06:37 UTC, yuji91 commented on README.md
> +仕入・在庫管理・販売の一連の流れを同一人物または小数人で行うような、小規模な事業関係者
ちなみにこのマーケットは主に「営業マン」を対象にしているのでしょうか？

2020-11-25 06:37 UTC, yuji91 commented on README.md
> +- 在庫管理＋需要予測、在庫管理＋棚卸といったアプリは探せば見つかったが、収支を見れるような営業マン寄りのアプリはなかったため。
同じ課題を抱えている人に刺さりそうで、良いと思います！

2020-11-25 06:37 UTC, yuji91 commented on README.md
> +→入出荷データを、入荷データ一覧と出荷データ一覧に切り分けて、それぞれの合計数量で引算する方が良さそうか。
この記載だけだと内容が読み取れなかったので、具体的なデータなどあると解答しやすいですね。
（アプリがある程度できるまで保留でも大丈夫です！）

2020-11-25 11:20 UTC, naka-no-mura commented on README.md
> +# Z-SHIHAN（ジー・シハン）
・在庫（ZAIKO）の頭文字で、Z。
・現在私が所属している会社で使っている会計処理のシステムが、「仕入販売システム」という名前であり、略して「しはん」と読んでいます。
この2つを合わせた名前にしました。

完全に、自分の現在の会社で使うことだけを考えて、このような名前にしましたが、確かに外部の方からしたらサービス名から機能が想像できないですよね、、、

補足説明：
サービス名は、「在庫」「仕入」「販売」の頭文字からとりました。

このように一行付け足すと、名前の由来はイメージつきそうでしょうか？

2020-11-25 11:44 UTC, naka-no-mura commented on README.md
> +仕入・在庫管理・販売を担うビジネスパーソンのために
`メーカーの営業職のような、仕入・在庫管理・販売を担うビジネスパーソンのために`

まさにこのことをお伝えしたかったので、このまま使わせてください！

2020-11-25 12:02 UTC, naka-no-mura commented on README.md
> +在庫管理と収支管理の一体型サービスです
確かに細かすぎますね、、、

`メーカーの営業職のような、仕入・在庫管理・販売を担うビジネスパーソンのために`
`商品の在庫と売り上げの収支をリアルタイムで管理できるサービスです。`

すごく腑に落ちてしまったので、こちらを使わせていただきたいです！

2020-11-25 12:15 UTC, naka-no-mura commented on README.md
> +- 販売業務を行う人
この書き方だと、仕入担当者、倉庫管理者、販売担当者の最低3人が登場する、という意味で捉えられてしまいますよね、、、

あくまで、
`・仕入業務：仕入れ元と価格交渉を行い、仕入価格を決める`
`・在庫管理：入荷・出荷の手配を行い、在庫を適正に保つ`
`・販売業務：販売価格を決め、商品を売る`
`この3つを1人で行うようなビジネスモデルに携わる人`
という意味でサービスを考えていました。
この説明で伝わりそうでしょうか？

私自身が、1人で川上から川下まで担当するような仕事をしており、1つずつの管理がバラバラのため、いちいち時間をかけて各々を確認しないと正確な収支が見えてこない、という課題を持っています。
1人で行うため時間もないので、効率よく3つとも一気に管理できたらなというニュアンスです！

大きな会社だとこの3つが部署ごとに分かれていて、担当が異なることが多いかと思いますが、中小企業や小さい課だと、私のような悩みを持った人も多いのでは？と思ったので！

2020-11-25 20:31 UTC, naka-no-mura commented on README.md
> +→入出荷データを、入荷データ一覧と出荷データ一覧に切り分けて、それぞれの合計数量で引算する方が良さそうか。
画面遷移とER図も作ってあるので、READMEをmergeしてからご相談させてください！

2020-11-25 20:32 UTC, naka-no-mura commented on README.md
> +- 在庫管理＋需要予測、在庫管理＋棚卸といったアプリは探せば見つかったが、収支を見れるような営業マン寄りのアプリはなかったため。
ありがとうございます！

2020-11-25 21:11 UTC, naka-no-mura commented on README.md
> +（販売先Aでこれだけ収益が出ているから、販売先Bでは販売単価を下げて数量拡大に努めよう、という戦略が立てられる）
> 「売買損益が確認できる」ことで「営業マンのための在庫管理サービスとなる」ことの関連性がうまく理解できませんでした。

一般的な営業マンは、販売先へのアフターフォローだったり新規営業が主な仕事であるため、「在庫は常に存在するもの」として営業をする、また、「仕入元との価格交渉」は別の担当が行う、という考えのもと、このような書き方をしました。

`・仕入業務：仕入れ元と価格交渉を行い、仕入価格を決める`
`・在庫管理：入荷・出荷の手配を行い、在庫を適正に保つ`
`・販売業務：販売価格を決め、商品を売る`
`この3つの業務を1人で行うようなビジネスモデルに携わる「なんでも営業マン」`
このような3つの業務を1人で行う人を「なんでも営業マン」と呼ぶならば、
川上から川下までを1人で全て担うわけなので、営業をしながら、仕入価格を把握し（＝販売価格と仕入価格の両方を考えるので収支を考えることは必須）、在庫の調整も行う必要がある。という意味で、「売買損益が確認できる」→「営業マンのための在庫管理サービスとなる」という流れにしました。


- `仕入業務を行う人`
- `在庫管理を行う人`
- `販売業務を行う人`
登場人物のところで、最初に記載したこの表現から
`・仕入業務：仕入れ元と価格交渉を行い、仕入価格を決める`
`・在庫管理：入荷・出荷の手配を行い、在庫を適正に保つ`
`・販売業務：販売価格を決め、商品を売る`
`この3つの業務を1人で行うようなビジネスモデルに携わる「なんでも営業マン」`
こちらの表現へ変えれば、
`売買損益が確認できるため、なんでも営業マンのための収支・在庫管理サービスとなり得る  `
この関連性も伝わるかなと思ったのですが、いかがでしょうか？


> ここでいう「営業マン」とは「仕入、在庫管理、販売」を行なっているということでしょうか。

おっしゃる通りです。
`・仕入業務：仕入れ元と価格交渉を行い、仕入価格を決める`
`・在庫管理：入荷・出荷の手配を行い、在庫を適正に保つ`
`・販売業務：販売価格を決め、商品を売る`
`この3つを1人で行うようなビジネスモデルに携わる人`

この人のことを「営業マン」という意味で書きましたが、分かりづらいですよね、、、

登場人物のところで、
`・仕入業務：仕入れ元と価格交渉を行い、仕入価格を決める`
`・在庫管理：入荷・出荷の手配を行い、在庫を適正に保つ`
`・販売業務：販売価格を決め、商品を売る`
`この3つを1人で行うようなビジネスモデルに携わる「なんでも営業マン」`
このように、「なんでも営業マン」と定義してしまえば、一言で伝わるかなと主観では思いました！いかがでしょうか？

2020-11-25 21:22 UTC, naka-no-mura commented on README.md
> +仕入・在庫管理・販売の一連の流れを同一人物または小数人で行うような、小規模な事業関係者
おっしゃるとおりです！

`同一人物または小数人で行うような、小規模な事業関係者`この表現だと、全体的に定義の仕方がバラバラになるので伝わりづらいですよね。
ここでも、`仕入・在庫管理・販売の一連の流れを1人で担うような「なんでも営業マン」`という表現にしてみようかなと思います。

2020-11-25 22:26 UTC, naka-no-mura commented on README.md
> +- 販売先によって販売額も設定できるため、売買損益が確認できる
> 「商品の価格を販売先ごとに設定できる」ということでしょうか。

おっしゃる通りです。
既存の在庫管理のサービスを色々調べると、在庫調整のみを行う「在庫管理者」のためのサービスが多く、シンプルに在庫の増減（入荷と出荷）に重点が置かれたものが多かったです。


> また商品の価格を販売先ごとに設定するのは、他の一般的なサービスでは出来ない機能ということですかね。

上でも述べたように、「在庫管理のみ」のものがほとんどで、「収支」まで把握できるサービスは見当たりませんでした。
https://www.zaico.co.jp/
こちらが人気のサービスのようですが、やはり在庫の増減のみでした。


> 「売買損益が確認できる」ということですが、販売先によって販売額が設定できない他サービスでは確認できないということでしょうか。

https://posregi.jp/nexpo/
こちらのサービスはかなり使いやすそうで、販売先によって販売額を設定できるため、一般的な「在庫管理」に加え、「売り上げ」も管理できるようでした。
しかし、やはり「仕入」に関しては入荷数量を反映させるだけで、「いくらで仕入れたものが、どこにいくらで販売できたか」といった販売先ごとの収支（＝売買損益）までは把握できないような仕組みでした。

例えば課長職以上になると、単純に「売り上げ」のみではなく、「仕入」も管理して課の利益がいくらなのか？この販売先に対していくら儲かっているのか？まで把握したいかと思います。
それを実現させたく、「在庫管理」「仕入価格」「販売価格」を1画面で把握できるようなサービスを作りたいと思っています。

私が考えているUIは下記のようなイメージで、販売先ごとの仕入価格、販売価格、収支（＝売買損益）が一眼でわかるようなものです！

<img width="1095" alt="スクリーンショット 2020-11-26 7 22 22" src="https://user-images.githubusercontent.com/67740798/100287541-2bc8cd00-2fb8-11eb-8f7c-7d54a5b0c845.png">

`販売先によって販売額も設定できるため、売買損益が確認できる`
ここをアピールしたいので、現状のこの表現ではなく、
`仕入額の設定に加え、販売先ごとの販売額も設定できるため、売買損益が一眼で確認できる`
この表現に変更しようかなと思いました！

2020-11-26 03:53 UTC, yuji91 commented on README.md
> +# Z-SHIHAN（ジー・シハン）
はい、1行細くすれば良いかと思います！

2020-11-26 04:02 UTC, yuji91 commented on README.md
> +- 販売業務を行う人
`商品の仕入、在庫管理、販売などの業務を担当する人`という記載で十分かと思います！

細かい業務の内容を説明しなくても、アプリの概要が伝わる内容に出来ると良いですね。

2020-11-26 04:10 UTC, yuji91 commented on README.md
> +- 販売先によって販売額も設定できるため、売買損益が確認できる
`在庫管理だけでなく、販売先ごとの収支を把握して販売戦略が立てられる`という説明で良い気がします！

`売買損益`のような専門用語はパッと見たときに分かりづらいので、出来るだけ噛み砕いた単語を使った方がイメージしやすいですね。

2020-11-26 04:20 UTC, yuji91 commented on README.md
> +（販売先Aでこれだけ収益が出ているから、販売先Bでは販売単価を下げて数量拡大に努めよう、という戦略が立てられる）
`営業マンが仕入や販売価格を把握できるようになり、在庫の調整や売り上げ戦略を立てられるようになる。`といった説明の方が分かりやすいかと思います。

> 営業マンのための在庫管理サービスとなる`

--> なぜ営業マンのためになるのかという部分が「在庫はもともと営業の管轄外で、営業も在庫情報を把握できることで業務の幅が広がる」という前提知識がないと理解できないと思います。

> このように「なんでも営業マン」と定義してしまえば

--> 一般に馴染みのない言葉を定義すると、それを変換して読み換える作業が発生して他の内容が読みづらくなってしまうかと思います。

> 売買損益が確認できるため、なんでも営業マンのための収支・在庫管理サービスとなり得る

--> 専門用語と、新しく定義した単語があるため分かりづらく、前提知識が必要な一文となっています。

どのくらい内容を噛み砕いた（一般に伝わりやすい）表現で伝えられるかと、前提知識はどのくらい伝える必要があるかで、サービスを説明する際に必要な情報が変わってくるかと思います。

2020-11-26 04:21 UTC, yuji91 commented on README.md
> +仕入・在庫管理・販売の一連の流れを同一人物または小数人で行うような、小規模な事業関係者
`仕入・在庫管理・販売の一連の流れを1人で担うような営業職の方`という表現で十分かと思います。

2020-11-26 04:23 UTC, yuji91 requested changes
再度確認しました。

修正の際は、指摘事項ごとにコミットの単位を分けて、コミットIDを指摘事項ごとに返信頂けると確認がしやすいです。

2020-11-26 22:37 UTC, naka-no-mura commented on README.md
> +# Z-SHIHAN（ジー・シハン）
サービス名の由来を一言添えました。

2020-11-26 22:43 UTC, naka-no-mura commented on README.md
> +仕入・在庫管理・販売を担うビジネスパーソンのために
修正しました

2020-11-26 22:44 UTC, naka-no-mura commented on README.md
> +在庫管理と収支管理の一体型サービスです
修正しました

2020-11-26 22:46 UTC, naka-no-mura commented on README.md
> +- 販売業務を行う人
修正しました。

2020-11-26 22:55 UTC, naka-no-mura commented on README.md
> +- 販売先によって販売額も設定できるため、売買損益が確認できる
修正しました。

> 売買損益のような専門用語はパッと見たときに分かりづらいので、出来るだけ噛み砕いた単語を使った方がイメージしやすいですね。

言われてみると、確かに売買損益は専門用語ですよね、ありがとうございます！面接の時もここは気をつけようと思います！

2020-11-26 22:59 UTC, naka-no-mura commented on README.md
> +（販売先Aでこれだけ収益が出ているから、販売先Bでは販売単価を下げて数量拡大に努めよう、という戦略が立てられる）
修正しました。

>>営業マンのための在庫管理サービスとなる

> --> なぜ営業マンのためになるのかという部分が「在庫はもともと営業の管轄外で、営業も在庫情報を把握できることで業務の幅が広がる」という前提知識がないと理解できないと思います。

--> 自分の中の普通が、他の人にとって前提知識とイコールではないこと、戒めます！


>> このように「なんでも営業マン」と定義してしまえば

> --> 一般に馴染みのない言葉を定義すると、それを変換して読み換える作業が発生して他の内容が読みづらくなってしまうかと思います。

--> 闇雲に定義するのはよくないということですね、、！

2020-11-26 23:02 UTC, naka-no-mura commented on README.md
> +仕入・在庫管理・販売の一連の流れを同一人物または小数人で行うような、小規模な事業関係者
修正しました！

2020-11-26 23:09 UTC, naka-no-mura commented
> 再度確認しました。
> 修正の際は、指摘事項ごとにコミットの単位を分けて、コミットIDを指摘事項ごとに返信頂けると確認がしやすいです。

ご確認いただきありがとうございます！
「コミットの単位を分けて指摘事項ごとに返信」は、このやり方で大丈夫そうでしょうか？
返信方法に関して、まだ理想の形までいけてなかったら、また指摘していただけると幸いです！

githubの使い方にまだまだ抵抗があります笑
色々調べながらですが、早く呼吸するようにgithubを使えるようになりたいです。

あと、伊藤さんの「複雑な文章を噛み砕いてシンプルにする力」にすごく憧れています！！

2020-11-27 04:07 UTC, yuji91 commented on README.md
> +仕入・在庫管理・販売を担うビジネスパーソンのために
ccb518a で修正を確認しました。

2020-11-27 04:08 UTC, yuji91 commented on README.md
> +# Z-SHIHAN（ジー・シハン）
5400897 で修正を確認しました。

2020-11-27 04:08 UTC, yuji91 commented on README.md
> +在庫管理と収支管理の一体型サービスです
ef963f1 で修正を確認しました。

2020-11-27 04:09 UTC, yuji91 commented on README.md
> +- 販売業務を行う人
8dcb7a6 で修正を確認しました。

2020-11-27 04:13 UTC, yuji91 commented on README.md
> +（販売先Aでこれだけ収益が出ているから、販売先Bでは販売単価を下げて数量拡大に努めよう、という戦略が立てられる）
e84fa36 で修正を確認しました。

2020-11-27 04:14 UTC, yuji91 commented on README.md
> +仕入・在庫管理・販売の一連の流れを同一人物または小数人で行うような、小規模な事業関係者
5cb061a で修正を確認しました。

2020-11-27 04:19 UTC, yuji91 commented on README.md
> +- どの販売先でどのくらい売買損益が発生しているのかをパッと見で把握できない
売買損益の発生を把握できないことで、ユーザーがどのように困るのかが伝わらないと思います。

どういったユーザーがどのような場面で困るのかを具体的に記載しましょう。

2020-11-27 04:21 UTC, yuji91 commented on README.md
> +- 営業マンが仕入や販売価格を把握し、収支を確認できるようになり、在庫の調整や売り上げ戦略を立てられるようになる。
「営業マンが仕入や販売価格を把握し、収支を確認できるようになり、在庫の調整や売り上げ戦略を立てられるようになる。」 --> この内容は`解決方法`の項目に記載するべき内容だと思います。

「在庫、仕分け、販売を一括で管理できるサービスは他にはありません。」と言う点を伝えた方が良いと思います。
代表的な他サービスのURLを紹介すると説得力が出るので記載して見てください。

2020-11-27 04:22 UTC, yuji91 requested changes
改めて気になった点を指摘しました。

2020-11-27 04:25 UTC, yuji91 commented
> 返信方法に関して、まだ理想の形までいけてなかったら、また指摘していただけると幸いです！

コミットIDはリンクになるので、レビュアーの指摘事項についてどのコミットで対応したのか、その内容は何かを確認できるようになります。
レビュアーの指摘事項には「修正対象のコミットIDのリンクを連絡する」までが修正時のタスクだと考えてください。

これにより指摘事項の対応漏れや修正内容の成否がすぐに確認できます。

2020-11-27 06:06 UTC, naka-no-mura commented on README.md
> +- どの販売先でどのくらい売買損益が発生しているのかをパッと見で把握できない
#99c82e8

2020-11-27 06:09 UTC, naka-no-mura commented on README.md
> +- どの販売先でどのくらい売買損益が発生しているのかをパッと見で把握できない
99c8e28e60855c8887900b8abca7bb267c4961edで修正しました。

2020-11-27 07:33 UTC, naka-no-mura commented on README.md
> +- 営業マンが仕入や販売価格を把握し、収支を確認できるようになり、在庫の調整や売り上げ戦略を立てられるようになる。
9c8ebf8408b6cfc3c191ecd949f1454a5337cc52 で修正しました。

他の有名なサービスも3つ記載してみました。

2020-11-27 07:36 UTC, naka-no-mura commented
> コミットIDはリンクになるので、レビュアーの指摘事項についてどのコミットで対応したのか、その内容は何かを確認できるようになります。
> レビュアーの指摘事項には「修正対象のコミットIDのリンクを連絡する」までが修正時のタスクだと考えてください。

> これにより指摘事項の対応漏れや修正内容の成否がすぐに確認できます。

コミットIDのリンクまで連絡するのが通例とのこと、承知いたしました！
99c8e28
9c8ebf8 の2つ分が追加修正したコミットになります。

9c00ad1 はスペースを変えただけです。

再度よろしくお願いいたします！

2020-11-27 07:44 UTC, naka-no-mura commented on README.md
> +→入出荷データを、入荷データ一覧と出荷データ一覧に切り分けて、それぞれの合計数量で引算する方が良さそうか。
b9db7ec82e34a18e4c043738697e6ecc061ba794
悩んでいることはREADMEには不要なので、こちらのコミットで削除しました。

2020-11-27 07:45 UTC, naka-no-mura commented
b9db7ec82e34a18e4c043738697e6ecc061ba794
「悩んでいること」はREADMEでは不要なので、こちらのコミットで削除しました。

2020-11-27 07:54 UTC, yuji91 approved these changes
最初と比べて大分伝わりやすさが改善されたかと思います！

どのような点に気をつけると相手に伝わりやすい内容になるのかについては、軽く振り返っておくと今後役立てられるかと思います。

2020-11-27 10:23 UTC, merged