[add]画面遷移図
naka-no-mura/z_shihan pull request #2
Opened 2020-11-27 10:41 UTC by naka-no-mura

ラフ画を追加しました。
デザインはひとまず、構成と導線を意識して作成しました。
よろしくお願いいたします。

2020-11-30 04:24 UTC, yuji91 requested changes
全体的にURLとアクション名を同じにしがちだったので、
一度Railsガイドのルーティングを確認しながらURLを見直した方が良いかと思います！

またこの指摘事項が入ったバージョンのXDファイルはバックアップを残して置いて欲しいので、指摘事項の修正は新しいXDのURLを提出する形でお願いしたいのですが、可能でしょうか？
（今回の指摘事項が残ったファイルと、指摘事項を修正したファイルの2つを確認できる形にして頂きたいですm(_ _)m）

2020-12-04 12:24 UTC, naka-no-mura commented
・2回目（修正後）
[Z-SHIHAN_2.xd.zip](https://github.com/naka-no-mura/z_shihan/files/5642674/Z-SHIHAN_2.xd.zip)

2020-12-07 07:44 UTC, yuji91 commented
すみません。zipファイルだと複数人のレビュアーで確認してコメントできないので、URLの形式で送って頂きたいです。

前回のレビュー指摘のあった状態のXDを残して欲しいと自分が依頼していたので、そちらのXDをzipとして切り出して、修正をおこなったものはURLで確認できるようにして頂くと良いかもしれません。

2020-12-07 22:05 UTC, naka-no-mura commented
失礼いたしました。
こちらでいかがでしょうか？
よろしくお願いいたします！

・修正前
[Z-SHIHAN.xd.zip](https://github.com/naka-no-mura/z_shihan/files/5655495/Z-SHIHAN.xd.zip)

・修正後：https://xd.adobe.com/view/bf5ae5fc-c352-4546-afe5-486ee58fbe0a-ea09/

2020-12-08 02:30 UTC, yuji91 commented
こちらコメントしました！
ちなみに前回の講師からのXDへのコメントはもう確認できないでしょうか？

2020-12-08 13:18 UTC, naka-no-mura commented
ご確認いただきありがとうございます！
今回は仕様を変えたわけではないので、XD上で返信のみさせていただきました。
https://xd.adobe.com/view/bf5ae5fc-c352-4546-afe5-486ee58fbe0a-ea09/


> ちなみに前回の講師からのXDへのコメントはもう確認できないでしょうか？

いろいろググってみたのですが、XD上での無料アカウントでは共有リンクは1つしか持てないという前提があり、
初回分の共有リンクを外しローカル上に保存し、修正分（2回目）で新たに共有リンクを設けると、初回分は見れないようです。。。

ただ、下記のスクリーンショットのように、右上のベルマークを押すと、コメントの履歴のみは見れました。
しかしコメントとアートボードは紐づいていないようです。
<img width="1680" alt="スクリーンショット 2020-12-08 22 04 07" src="https://user-images.githubusercontent.com/67740798/101487424-817e7b80-39a1-11eb-8ee1-6bc046dfb55d.png">

コメントをクリックして初回分に飛ぼうとしても、リンクは外してしまってるので案の定下記のように表示はされませんでした。
<img width="804" alt="スクリーンショット 2020-12-08 22 04 33" src="https://user-images.githubusercontent.com/67740798/101487433-83e0d580-39a1-11eb-8d42-5861e87eed1b.png">

2020-12-08 15:07 UTC, yuji91 approved these changes
修正確認したので、LGTMです！

2020-12-09 11:09 UTC, merged