add:ER図
naka-no-mura/z_shihan pull request #3
Opened 2020-12-09 22:38 UTC by naka-no-mura

# ER図
https://drive.google.com/file/d/1fNgbByW-FdsN_WC7Bfsl2i-Yj1ytJXH1/view?usp=sharing
<img width="1552" alt="スクリーンショット 2020-12-10 7 34 11" src="https://user-images.githubusercontent.com/67740798/101696878-255b4a80-3aba-11eb-8f39-b46d75692942.png">

# README
#1 

# 画面遷移図
#2 

# テーブルとカラムの説明

```
User:
  name: ユーザーの名前
  email: メールアドレス
  crypted_password: sorceryで認証
  salt: sorceryで認証

WarehouseMaster:（マスタ）
  name: 倉庫名

ProductMaster:（マスタ）
  name: 商品名

PackingStyleMaster:（マスタ）
  name: 荷姿名
  product_master_id: 商品名に依存

CustomerMaster:（マスタ）
  name: 販売先名

SellingPriceMaster:（マスタ）
  calendar: 年月
  selling_price: 販売単価

SupplierMaster:（マスタ）
  name: 仕入元名
  postal_code:  郵便番号
  address: 住所
  department: 部署名

PurchasePriceMastr:（マスタ）
  calendar: 年月
  purchase_price: 仕入単価

PrefectureMaster:（マスタ）
  name: 県名
  最初の開発段階でSQLで47都道府県を登録しておき、サービス上でユーザーがわざわざ登録する必要のないようにする。
  サービス上ではプルダウンで県名を選択するのみとする。

MiddleOrder:（中間テーブル）
  calendar: ◯◯◯◯年△△月
（カレンダーをマスタにするのは違和感があったため、「倉庫一覧/倉庫◯/年月一覧」の画面でユーザーが新規追加する。）
  warehouse_master_id、calendar、packing_style_master_id、product_master_id、user_id、customer_master_id、supplier_master_idの7つのカラムを1セットと考えた時に、ユニークになるようにする。

OrderHeaders:
  stock: 現在庫数（入庫数ー出庫数を計算した値を表示）
  last_purchase_price: 最終仕入単価（最後に仕入れた単価が自動で入るようにしたい）
  inventory: 棚卸金額（現在庫数＊最終仕入単価を計算した値）
  total_profit: 売買損益の合計（「倉庫＞月＞商品＞荷姿」この項目の収支が分かる）

OrderDetails:
  state: 出荷か入荷（enumで管理）
  day: 何日に出荷/入荷するレコードなのか
  number: 指図番号
  quantity: 出荷/入荷の数量
  selling_price: 販売単価
  profit: レコードごとの売買損益単価
  total_profit: 売買損益合計（収支）
```

# 悩んでいること
`OrderHeadersテーブル`で`stock: 現在庫数`をどういう仕組みで表示させるか。  
出荷はマイナス、入荷はプラスで、その合計値を表示すれば良いと考えているが、どうやって「出荷の値なのか」「入荷の値なのか」を判別させるべきなのかがイメージできていない。`enum`と紐づければ行けそうか。

2020-12-11 05:12 UTC, yuji91 commented
マスタ系テーブルに`Master`という文字列はテーブル名、モデル名に付けることは一般的には無いという点は大丈夫でしょうか？（基礎編、応用編の課題でもMasterというテーブル、モデルは無かったですよね。）

2020-12-11 06:59 UTC, yuji91 commented
各Master系テーブルで`user_id`を持つ必要はありますか？
※ 例えば倉庫Aを作成したとして、作成者のID情報を倉庫Aのレコードに持たせる必要はないかと思います。

OrderHeaderとOrderDetailはどのように使い分ける想定のテーブルでしょうか？
Orderという1モデルではなく分けている点の説明をお願いしたいです。

2020-12-11 07:00 UTC, yuji91 requested changes
一旦気になった点を先に解消した方が良いと思うので、悩んでいる点には言及していません。

また修正の際は記録を取りたいので、PullRequestの最初の画像は残したままで、修正後の内容をコメントして追記する形でお願いします。

2020-12-11 07:46 UTC, naka-no-mura commented
> マスタ系テーブルに`Master`という文字列はテーブル名、モデル名に付けることは一般的には無いという点は大丈夫でしょうか？（基礎編、応用編の課題でもMasterというテーブル、モデルは無かったですよね。）

2020-12-11 07:54 UTC, naka-no-mura commented
> マスタ系テーブルにMasterという文字列はテーブル名、モデル名に付けることは一般的には無いという点は大丈夫でしょうか？（基礎編、応用編の課題でもMasterというテーブル、モデルは無かったですよね。）

おっしゃる通りですね、、、マスタであることを明示したかったですが、その必要はなさそうなので修正いたしました。
マスタ系テーブル名に「Master」とつけていた名前部分のみ削除しました。
<img width="1553" alt="スクリーンショット 2020-12-11 16 52 57" src="https://user-images.githubusercontent.com/67740798/101877434-58dcc880-3bd1-11eb-82bc-cfb8449368ce.png">

2020-12-11 08:12 UTC, naka-no-mura commented
> 各Master系テーブルでuser_idを持つ必要はありますか？
> ※ 例えば倉庫Aを作成したとして、作成者のID情報を倉庫Aのレコードに持たせる必要はないかと思います。

自分だけが仕事でこのサービスを使うのであれば、各Master系テーブルでuser_idを持つ必要はなさそうです。
ただ、後々全く別の人がこのサービスを使うことを想定すると、`user_id`に紐付けた方がいいのかなと考えました。自分にとっては必要な倉庫名でも、別の人にとっては必要のない倉庫名であることもあるかと思ったためです。
ログインしているuser: idと紐づいている、`user_id`を持つマスタ情報のみ表示させるつもりでした。
県名に関しては、誰であっても必要であると考えたため、`user_id`には紐付けていません。

しかし、直近では自分の業務を効率化するために作成しているサービスであって、想定している使用場面は、課内での使用のみです。
直近だけのことを考えると、そもそも`userテーブル`自体が不要なのでは？とも考えています。

ただ、勉強したことをポートフォリオに組み込みたいとの想いもあり、userテーブルの作成を考えました。
SNSアカウントでのログインにはAPIの知識も必要かと思いますし、APIについて学習したことも表現できるのでは？と思った次第です。

やはりサービスに不要なものは実装しないことを優先させるべきでしょうか？
アドバイスをいただければ幸いです！

2020-12-11 09:12 UTC, naka-no-mura commented
> OrderHeaderとOrderDetailはどのように使い分ける想定のテーブルでしょうか？
> Orderという1モデルではなく分けている点の説明をお願いしたいです。

# 現状
`OrderHeader`テーブルの`last_purchase_price（最終仕入単価）`と`inventory（棚卸金額）`は毎回使うカラムではなく、棚卸時にしか使用しないため（自動計算で常に表示させる必要性はない）、`OrderDetail`と合体して1テーブルとしてしまうと、カラムに空きができている状態となり、良くないテーブル設計となってしまうと考えたからです。


<img width="1279" alt="スクリーンショット 2020-12-11 17 18 56" src="https://user-images.githubusercontent.com/67740798/101879806-38af0880-3bd5-11eb-9aaf-5716695e9a95.png">

＜1＞`OrderHeader`は、上記の画面でいう、こちらの部分にあたる想定です。
<img width="1141" alt="スクリーンショット 2020-12-11 17 17 41" src="https://user-images.githubusercontent.com/67740798/101879907-65632000-3bd5-11eb-9c53-460041e09923.png">
この部分は、各レコードの入出荷数量を計算した値を入れる「現在庫」や、各レコードの売買損益を計算した値を入れる「売買損益合計」等を表示させるために作りたかったテーブルになります。
あくまで、**各レコード同士の値を計算した値を入れるテーブル**になります。

＜2＞一方、`OrderDetail`は、上記の画面でいう、こちらの部分にあたる想定です。
<img width="1142" alt="スクリーンショット 2020-12-11 17 18 33" src="https://user-images.githubusercontent.com/67740798/101879966-7dd33a80-3bd5-11eb-87c8-990c7ea23252.png">
この部分は、**入出荷データの1レコードの値を入れるテーブル**になります。

合計を表示させる部分と、1レコードを表示させる部分を同じテーブルにすると不具合が発生するだろうと思ったので、このように2つのテーブルに分けました。

# 変更

しかし、ここまで考えた上でですが、「在庫管理」という機能において、「現在庫数」のみ分かれば、「棚卸金額」と「売買損益合計」をこの画面で表示させる必要は無いのでは？とも思ってきました。
在庫管理サービスにおいて「棚卸金額」の表示は必須と考えていましたが、正直、現業務でこのサービスを使用するという点で考えると、「棚卸金額」と「売買損益合計」をこの画面では必要としていません。
別のページで「収支実績」という画面も設けていますし、そちらで確認できれば、「棚卸金額」と「売買損益合計」は、この画面では不要かと考えました。

それを踏まえて、テーブル設計を再度考えました。
<img width="1545" alt="スクリーンショット 2020-12-11 17 51 34" src="https://user-images.githubusercontent.com/67740798/101882713-98a7ae00-3bd9-11eb-8f3c-dd20cbfffc10.png">

【変更点】
- `OrderHeader`と`OrderDetail`を`Order`という1テーブルとした。
- `last_purchase_price（最終仕入単価）`、`inventory（棚卸金額）`、`profit（損益単価）`、`total_profit（損益単価合計）`カラムを削除した。
- `Stock`テーブル（在庫数）を作成し、各レコードの入出荷数量の値を計算した値を入れるようにしたい。

2020-12-11 09:15 UTC, naka-no-mura commented
長文になってしまったため、要点が分かりづらくなっていたら申し訳ございません。
再度ご確認お願いいたします！

> また修正の際は記録を取りたいので、PullRequestの最初の画像は残したままで、修正後の内容をコメントして追記する形でお願いします。

また、こちらに関して、このやり方で合ってますでしょうか？間違っていたらご指摘いただければと思います！

2020-12-11 09:48 UTC, yuji91 commented
Ordersテーブルのdayという日付はカラム名から何の日付データかが分からないので、具体的なカラム名にしましょう。

2020-12-11 10:12 UTC, naka-no-mura commented
> Ordersテーブルのdayという日付はカラム名から何の日付データかが分からないので、具体的なカラム名にしましょう。

`delivery_day`（入荷or出荷日）としました。

2020-12-11 10:17 UTC, DaichiSaito commented
入荷 or 出荷を意味するカラム名がstateというのが違和感ありました。

OrderとOrderHeaderを統合したとのことですが、売買損益単価や売買損益合計がOrderにあるのはおかしくないでしょうか。

Orderに在庫が紐づいてるのって何か直感的におかしいような気がします。

「何月」の最終的な入出庫記録を取っておきたいのであればそれ用のテーブルも必要そう？

伊藤くんも言ってますがやはりUserテーブルの必要性があまり感じられない、、、仮にユーザーと倉庫を紐付けるとしても多対多の関係になりそうじゃないですか？

他のテーブルとの関係も同様かな...？

参考までにレンタルショップのテーブル構成を置いておきます。
https://dev.mysql.com/doc/sakila/en/sakila-structure.html
![sakila-schema](https://user-images.githubusercontent.com/10973259/101890482-17094d80-3be4-11eb-995d-53af59f10558.png)

2020-12-11 10:20 UTC, naka-no-mura commented
> Calendarには「2020年11月」などの文字列がStringとして記載されますか？

そのつもりでした。
<img width="844" alt="スクリーンショット 2020-12-11 19 13 49" src="https://user-images.githubusercontent.com/67740798/101891168-05747580-3be5-11eb-8b62-656c984357cc.png">

このページの表現方法に悩んでいます。
倉庫名のようにマスタで管理することも考えましたが、年月をマスタで管理するのは違和感があったのと、倉庫在庫を月毎に管理したかったので、文字列として`string`という形にしてみました。

`MiddelOrderテーブル`を取り払い、`calendarカラム`を`Orderテーブル`に持ってくると、`delivery_dayカラム`と2つある意味がなさそうでしょうか？

2020-12-11 10:33 UTC, naka-no-mura commented
> Orderは入出荷一覧に登録される1行のデータが元になると思うのですが、MiddleOrdersという中間テーブルを使う形式である必要性はありますか？
> （Calendarなどの付属した情報はすべてIDでカラムで持たせておくことに問題はあるのでしょうか。）

多対多かと思っていましたが、倉庫：入出荷データ＝1：多の関係かと思うので、MiddleOrdersは取り払います。

2020-12-12 04:30 UTC, naka-no-mura commented
色々修正が必要かと思ったので、いただいたSQLのサンプルデータも参考にしながら、ER図をガラッと修正しました。
「PHP　在庫管理」で検索すると参考になるような記事がたくさんあり、シンプルなものであれば、「商品テーブル」「在庫テーブル」「オーダーテーブル」のみで作成できるようでしたので、そちらからもヒントをもらいました。

## 修正後

<img width="1329" alt="スクリーンショット 2020-12-12 13 12 59" src="https://user-images.githubusercontent.com/67740798/101973487-e2e16b80-3c7b-11eb-9f36-3ab43286a635.png">



## テーブル説明
```
Warehouse（倉庫）:
  name: 倉庫名

Calendar（年月）:
  year_month: 年月（string型で「2020年11月」のように文字列が入る想定）

Product（商品）:
  name: 商品名

PackingStyle（荷姿）:
  name: 荷姿名

LastMonthStock（先月末在庫）:
  quantity: 先月末在庫数量を手入力（2020年11月を新規作成したときに、2020年10月の月末在庫を自動で入るようにはしない）

Stock（在庫）:
  quantity: 在庫数量

Arrival（入荷）:
  quantity: 入荷数量
  lot_number: ロット番号
  arrival_date: 入荷日

Supplier（仕入元）:
  name: 仕入元名
  postal_code: 郵便番号
  address: 住所
  department: 部署

PurchasePrice（仕入単価）:
  arrival_date: 購入日
  purchase_price: 仕入単価

Shipment（出荷）:
  quantity: 出荷数量
  order_number: 指図番号
  shipment_date: 出荷日

Customer（販売先）:
  name: 販売先名

Prefecture（県）:
  name: 県名

SellingPrice（販売単価）:
  shipment_date: 販売日
  selling_price: 販売単価

Balance（損益単価）:
  unit_margin: 売買損益単価（仕入単価ー販売単価）
  total_margin: 売買損益単価合計（売買損益単価×出荷数量）
```

## 主な変更点
- `Userテーブル`を削除しました。
- `Orderテーブル`をなくし、`Arrival（入荷テーブル）`と`Shipment（出荷テーブル）`で入荷と出荷を別テーブルで管理するようにしました。
- `arrival_date`、`shipping_date`とすることで入荷日と出荷日と分かるようなカラム名にしました。
- ` Calenderテーブル`で「2020年11月」と文字列でユーザーが登録するように変更。※これでいいのか？とまだ迷走中です。
- 「倉庫」「年月」「商品」「荷姿」同士は多対多になると思ったので、中間テーブルを作りました。
- 「売買損益単価」や「売買損益合計」を扱う、`Balanceテーブル`を作りました。
- 「先月末在庫」を扱う`LastMonthStockテーブル`を作りました。

2020-12-12 04:31 UTC, naka-no-mura commented
考え直してみました。
再度よろしくお願いいたします。

2020-12-14 09:19 UTC, DaichiSaito commented
- PackingStyles has_many Stocks に違和感を感じました。
「バラ」や「20kg」と「在庫」って直接紐づくものではないかなーと。

- Stocks belongs_to LastMonthStocks や LastMonthStock自体も違和感を感じました。
やるなら「先月」と決め打ちするのではなく「MonthStock」とかなのかなと思いました。


ただちょっと仕様がかなり複雑なのと中村さん自体も仕様やユースケースが曖昧な状態だと思うので、一旦作り始めてトライアンドエラーでやっていくのが良いかなと思いました！

2020-12-14 22:35 UTC, naka-no-mura commented
<img width="1336" alt="スクリーンショット 2020-12-15 7 35 00" src="https://user-images.githubusercontent.com/67740798/102143982-17396f80-3ea8-11eb-9daa-0b21de3d39a6.png">


> PackingStyles has_many Stocks に違和感を感じました。
> 「バラ」や「20kg」と「在庫」って直接紐づくものではないかなーと。

SQLのと同じように、シンプルに、`Warehouses has_many Stocks` 、 `Products has_many Stocks` にしてみました。

> Stocks belongs_to LastMonthStocks や LastMonthStock自体も違和感を感じました。
> やるなら「先月」と決め打ちするのではなく「MonthStock」とかなのかなと思いました。

こちらも、テーブル名は`MonthEndStocks`として、「先月」に限らず「月末在庫」を入れるテーブルとして、`Warehouses　has_many MonthEndStocks` になるようにしました。

2020-12-14 22:38 UTC, naka-no-mura commented
こちら、もう一度ご確認いただけると嬉しいです！
なかなか思うように進まないので、この最後のER図で作り始めてしまい、過不足がわかってきたら手直しするようにしていこうかと考えています。

お手数ですが、よろしくお願いいたします。

2020-12-18 23:14 UTC, merged